---
- name: 'Add the snowflake zypper repository'
  hosts: 'all'
  gather_facts: true
  become: true

  roles:
    - role: 'johanneskastl.add_zypper_repository'
      repository_name: 'home-ojkastl_buildservice-snowflake'
      repository_baseurl: "https://download.opensuse.org/repositories/home:/ojkastl_buildservice:/snowflake/{{ ansible_distribution_version }}/"
      auto_import_keys: '1'
      when:
        - ansible_distribution == 'openSUSE Leap'
